import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  // ── Core data (always seeded) ─────────────────────────────────────────────

  const [newnham, senecaYork, king] = await Promise.all([
    prisma.campus.upsert({
      where: { campusName: 'Newnham' },
      update: {},
      create: {
        campusName: 'Newnham',
        address: '1750 Finch Ave E, Toronto, ON M2J 2X5',
        retentionDays: 30,
      },
    }),
    prisma.campus.upsert({
      where: { campusName: 'Seneca@York' },
      update: {},
      create: {
        campusName: 'Seneca@York',
        address: '70 The Pond Rd, Toronto, ON M3J 3M6',
        retentionDays: 30,
      },
    }),
    prisma.campus.upsert({
      where: { campusName: 'King' },
      update: {},
      create: {
        campusName: 'King',
        address: '13990 Dufferin St, King City, ON L7B 1B3',
        retentionDays: 30,
      },
    }),
    prisma.campus.upsert({
      where: { campusName: 'Peterborough' },
      update: {},
      create: {
        campusName: 'Peterborough',
        address: '1717 Lansdowne St W, Peterborough, ON K9J 7B1',
        retentionDays: 30,
      },
    }),
  ]);

  console.log('Campuses: Newnham, Seneca@York, King, Peterborough');

  const adminHash = await bcrypt.hash('Admin@1234', 12);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@myseneca.ca' },
    update: {},
    create: {
      campusId: newnham.campusId,
      email: 'admin@myseneca.ca',
      username: 'admin',
      passwordHash: adminHash,
      role: 'admin',
      firstName: 'System',
      lastName: 'Admin',
      isActive: true,
    },
  });

  console.log(`Admin: ${admin.email} / Admin@1234`);

  // ── Dev sample data (skipped in production) ───────────────────────────────

  if (process.env.NODE_ENV === 'production') {
    console.log('Skipping dev sample data (production)');
    return;
  }

  const testHash = await bcrypt.hash('Test1234!', 12);

  const [alice, bob, carol] = await Promise.all([
    prisma.user.upsert({
      where: { email: 'alice@myseneca.ca' },
      update: {},
      create: {
        campusId: newnham.campusId,
        email: 'alice@myseneca.ca',
        username: 'alice',
        passwordHash: testHash,
        role: 'student',
        firstName: 'Alice',
        lastName: 'Smith',
        studentNumber: BigInt('123456789'),
        isActive: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'bob@myseneca.ca' },
      update: {},
      create: {
        campusId: senecaYork.campusId,
        email: 'bob@myseneca.ca',
        username: 'bob',
        passwordHash: testHash,
        role: 'student',
        firstName: 'Bob',
        lastName: 'Kim',
        studentNumber: BigInt('987654321'),
        isActive: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'carol@myseneca.ca' },
      update: {},
      create: {
        campusId: newnham.campusId,
        email: 'carol@myseneca.ca',
        username: 'carol',
        passwordHash: testHash,
        role: 'security',
        firstName: 'Carol',
        lastName: 'Jones',
        isActive: true,
      },
    }),
  ]);

  console.log(
    'Dev users: alice, bob (students) + carol (security) / Test1234!'
  );

  // Sample report link generated by carol
  const reportLink = await prisma.reportLink.upsert({
    where: { token: 'dev-sample-token-abc123' },
    update: {},
    create: {
      token: 'dev-sample-token-abc123',
      generatedBy: carol.userId,
      campusId: newnham.campusId,
      expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    },
  });

  // Sample found item report submitted by alice via the report link
  const existingReport = await prisma.foundItemReport.findFirst({
    where: { reportLinkId: reportLink.linkId, finderId: alice.userId },
  });
  if (!existingReport) {
    await prisma.foundItemReport.create({
      data: {
        reportLinkId: reportLink.linkId,
        finderId: alice.userId,
        itemDescription: 'White AirPods Pro case with small sticker',
        category: 'Electronics',
        locationFound: 'Near Tim Hortons, Newnham Campus',
        dateFound: new Date('2026-05-10'),
        additionalNotes: 'Found it on a bench outside Tim Hortons',
        status: 'submitted',
      },
    });
  }

  // Sample item registered by carol
  const existingItem = await prisma.item.findFirst({
    where: { registeredBy: carol.userId, title: 'AirPods Pro - White Case' },
  });
  if (!existingItem) {
    await prisma.item.create({
      data: {
        campusId: newnham.campusId,
        category: 'Electronics',
        title: 'AirPods Pro - White Case',
        descriptionPublic: 'White AirPods Pro case with sticker',
        descriptionInternal:
          'White AirPods Pro case with a small round sticker on lid.',
        color: 'white',
        brand: 'Apple',
        locationFound: 'Near Tim Hortons, Newnham Campus',
        dateFound: new Date('2026-05-10'),
        status: 'stored',
        registeredBy: carol.userId,
        retentionExpiryDate: new Date('2026-06-09'),
      },
    });
  }

  // Sample claim submitted by bob
  const existingClaim = await prisma.claim.findFirst({
    where: { studentId: bob.userId, category: 'Electronics' },
  });
  if (!existingClaim) {
    await prisma.claim.create({
      data: {
        studentId: bob.userId,
        campusId: newnham.campusId,
        category: 'Electronics',
        description:
          'Lost my AirPods Pro with white case. Has a small round sticker on the lid.',
        dateLost: new Date('2026-05-10'),
        locationLost: 'Near Tim Hortons or the library, Newnham Campus',
        status: 'submitted',
      },
    });
  }

  let hoodieItem = await prisma.item.findFirst({
    where: { registeredBy: carol.userId, title: 'Black Hoodie' },
  });
  if (!hoodieItem) {
    hoodieItem = await prisma.item.create({
      data: {
        campusId: senecaYork.campusId,
        category: 'Clothing',
        title: 'Black Hoodie',
        descriptionPublic: 'Black Seneca-branded hoodie, size M',
        descriptionInternal:
          'Black Seneca-branded hoodie, size M. Small tear on the left sleeve.',
        color: 'black',
        locationFound: 'Cafeteria',
        dateFound: new Date('2026-05-18'),
        status: 'stored',
        registeredBy: carol.userId,
        retentionExpiryDate: new Date('2026-06-17'),
      },
    });
  }

  let chargerItem = await prisma.item.findFirst({
    where: { registeredBy: carol.userId, title: 'Apple USB-C Charger' },
  });
  if (!chargerItem) {
    chargerItem = await prisma.item.create({
      data: {
        campusId: newnham.campusId,
        category: 'Electronics',
        title: 'Apple USB-C Charger',
        descriptionPublic: 'Apple 67W USB-C power adapter',
        descriptionInternal:
          'Apple 67W USB-C power adapter, no cable attached.',
        color: 'white',
        brand: 'Apple',
        locationFound: 'Room A4040',
        dateFound: new Date('2026-05-10'),
        status: 'stored',
        registeredBy: carol.userId,
        retentionExpiryDate: new Date('2026-06-09'),
      },
    });
  }

  const sampleClaims = [
    {
      studentId: alice.userId,
      campusId: newnham.campusId,
      category: 'Electronics',
      description:
        'Silver MacBook Pro 14" with a Seneca sticker on the lid. Lost near the library study area.',
      dateLost: new Date('2026-05-20'),
      locationLost: 'Library — 2nd floor study area',
      status: 'submitted' as const,
      itemId: null,
    },
    {
      studentId: alice.userId,
      campusId: king.campusId,
      category: 'Accessories',
      description: 'White AirPods Pro case with a blue keychain attached.',
      dateLost: new Date('2026-05-15'),
      locationLost: 'Gym locker room',
      status: 'rejected' as const,
      itemId: null,
      reviewedBy: carol.userId,
      reviewedAt: new Date('2026-05-19T14:30:00.000Z'),
      rejectionReason: 'No matching found item in storage.',
    },
    {
      studentId: bob.userId,
      campusId: senecaYork.campusId,
      category: 'Clothing',
      description:
        'Black Seneca-branded hoodie, size M. Has a small tear on the left sleeve.',
      dateLost: new Date('2026-05-18'),
      locationLost: 'Cafeteria',
      status: 'approved' as const,
      itemId: hoodieItem.itemId,
      reviewedBy: carol.userId,
      reviewedAt: new Date('2026-05-22T10:00:00.000Z'),
    },
    {
      studentId: alice.userId,
      campusId: newnham.campusId,
      category: 'Electronics',
      description: 'Apple 67W USB-C power adapter, no cable attached.',
      dateLost: new Date('2026-05-10'),
      locationLost: 'Room A4040',
      status: 'under_review' as const,
      itemId: chargerItem.itemId,
      reviewedBy: carol.userId,
      reviewedAt: new Date('2026-05-17T09:15:00.000Z'),
    },
  ];

  for (const claim of sampleClaims) {
    const existing = await prisma.claim.findFirst({
      where: {
        studentId: claim.studentId,
        category: claim.category,
        locationLost: claim.locationLost,
      },
    });

    if (!existing) {
      await prisma.claim.create({ data: claim });
    }
  }

  console.log('Dev sample data: report link, found report, items, claims');
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
